### ISSUE TITLE
Homebridge Plugin Event Subscribe

### ISSUE THREAD

**Issue by donavanbecker** [hufftheweevil/august-connect#1]
Any advice or help you can give to get [events subscribe](https://github.com/hufftheweevil/august-api#events), built into my [homebridge-august](https://github.com/donavanbecker/homebridge-august/tree/beta-0.1.0) plugin?

**Comment by donavanbecker** [comment]
@hufftheweevil I got it working. Thanks your for this repo.

If you have time and can review the plugin and suggest any changes, that would be awesome!!

**Comment by hufftheweevil** [comment]
Sorry I didn't respond to your first message, I just returned from vacation. Glad to see you got it working. I've never done anything with Homebridge, but I'll take a look when I can to see how you implemented it.

**Comment by donavanbecker** [comment]
Thanks!

**Comment by donavanbecker** [comment]
when calling validate [here](https://github.com/donavanbecker/homebridge-august/blob/66f30970dc95943d5d41fd8a574fe7014a6573ca/src/platform.ts#L151), I am getting both of these logs, is that suppose to happen? 

```
FetchError: Status 409 (InvalidArgument): Verification code not found
Session validated!
```

and I am doing authorize [here](https://github.com/donavanbecker/homebridge-august/blob/66f30970dc95943d5d41fd8a574fe7014a6573ca/src/platform.ts#L154).

seems like this only happens on reboot of homebridge the second time after validating a 2nd time with the same code.

**Comment by hufftheweevil** [comment]
Looks like you're creating a new `installId` every time you run discovery, which is unnecessary. And you're saving the `validateCode` in the credentials, which is a useless code after it is used to validate.

Instead, you want to save the `installId` with the credentials, so that the next time you need to run discovery, or just reconnect, you don't need to verify and validate again. Also it's good to set a `isValidated` flag of some sort so that you know the verify/validate process was actually completed.

Try replacing [L141-L155](https://github.com/donavanbecker/homebridge-august/blob/66f30970dc95943d5d41fd8a574fe7014a6573ca/src/platform.ts#L141-L155) with something like this. You need a way to get the code from the user. Could be done with a simple `prompt()` in the browser, or using alternate methods depending on how homebridge works.
```js
if (!this.config.credentials) throw "No credentials"

if (!this.config.credentials.installId) {
  this.config.credentials.installId = this.api.hap.uuid.generate(`${this.config.credentials.augustId}`)
}

this.august = new August(this.config.credentials);
this.debugLog(superStringify(this.august));

if (!this.config.credentials.isValidated) {
  this.august.authorize();
  // A 6-digit code will be sent to your email or phone (depending on what you used for your augustId).
  // Need some way to get this code from the user.
  let validateCode = prompt("Enter the code sent to your email or phone:")
  let isValidated = await this.august.validate(validateCode);
  // If validated successfully, set flag for future use, and you can now use the API
  this.config.credentials.isValidated = isValidated;
  if (!isValidated) return
}
// ... continue with device discovery
```

**Comment by donavanbecker** [comment]
@hufftheweevil Thanks!

Any thoughts on [this](https://github.com/donavanbecker/homebridge-august/issues/21)?

**Comment by hufftheweevil** [comment]
The fact that `doorState` is `init` is new to me. I checked my known [definitions](https://github.com/hufftheweevil/august-api/blob/main/definitions.md) and don't see it anywhere. I don't think it has anything to do with the issue above, but I recommend adjusting that code first and seeing if it resolves the 2nd problem too

**Comment by donavanbecker** [comment]
@hufftheweevil i was able to work with how homebridge needs it to work: [new validate](https://github.com/donavanbecker/homebridge-august/blob/459045e7782f1e2d2ca535a48225b1c5b0db7262/src/platform.ts#L132-L207)

**Comment by hufftheweevil** [comment]
Sounds good. Closing for now. Any other issues, feel free to post again.
